### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fjs21** [mikeknoop/homebridge-meural#2]
Everything was working fine for about two weeks. I am getting this error as of two days ago:

> (node:12280) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'responseUrl' of undefined
>     at C:\Users\Fraser\AppData\Roaming\npm\node_modules\homebridge-meural\src\platformAccessory.ts:234:53
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at CanvasAccessory.updateActive (C:\Users\Fraser\AppData\Roaming\npm\node_modules\homebridge-meural\src\platformAccessory.ts:229:7)
> (node:12280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1510)

Any ideas?

**Comment by mikeknoop** [comment]
Can you update to the latest version? There is better error logging place now that should reveal the true error (this was a bug in the original error catching logic).
